version: '2'

networks:
  app-tier:
    driver: bridge

services:
  minio:
    image: 'minio'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123123za
    networks:
      - app-tier
  myapp:
    image: 'bitnami/minio'
    networks:
      - minio-network
    environment:
      - MINIO_SERVER_ACCESS_KEY=admin
      - MINIO_SERVER_SECRET_KEY=admin
